import os

from reportlab.platypus import (
    Paragraph,
    Image,
    Spacer,
    PageBreak
)

from reportlab.lib.units import inch

from StoryCanvasAI.backend.pdf_engine.pdf_styles import (
    TITLE_STYLE,
    SUBTITLE_STYLE,
    HEADING_STYLE,
    BODY_STYLE,
)


def resize_image(img, max_width=5.8 * inch, max_height=6 * inch):
    """
    Preserve image aspect ratio while fitting inside the page.
    """

    width = img.imageWidth
    height = img.imageHeight

    scale = min(max_width / width, max_height / height)

    img.drawWidth = width * scale
    img.drawHeight = height * scale

    return img


def add_cover(elements, story):

    # -------------------------------------------------
    # Project Name
    # -------------------------------------------------

    elements.append(
        Paragraph(
            "StoryCanvas AI",
            TITLE_STYLE
        )
    )

    elements.append(
        Spacer(1, 0.15 * inch)
    )

    # -------------------------------------------------
    # Story Title
    # -------------------------------------------------

    elements.append(
        Paragraph(
            story["title"],
            SUBTITLE_STYLE
        )
    )

    elements.append(
        Spacer(1, 0.1 * inch)
    )

    # -------------------------------------------------
    # Genre
    # -------------------------------------------------

    elements.append(
        Paragraph(
            f"<b>Genre:</b> {story['genre']}",
            BODY_STYLE
        )
    )

    elements.append(
        Spacer(1, 0.6 * inch)
    )

    # -------------------------------------------------
    # AI Models Used
    # -------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Created using</b>",
            SUBTITLE_STYLE
        )
    )

    elements.append(
        Spacer(1, 0.1 * inch)
    )

    elements.append(
        Paragraph(
            "• Qwen2.5-VL-3B-Instruct",
            BODY_STYLE
        )
    )

    elements.append(
        Paragraph(
            "• FLUX.1-schnell",
            BODY_STYLE
        )
    )

    elements.append(
        Paragraph(
            "• Kokoro-82M",
            BODY_STYLE
        )
    )

    elements.append(
        Spacer(1, 0.5 * inch)
    )

    # -------------------------------------------------
    # Footer Text
    # -------------------------------------------------

    elements.append(
        Paragraph(
            "────────────────────────────────────────────",
            BODY_STYLE
        )
    )

    elements.append(
        Spacer(1, 0.15 * inch)
    )

    elements.append(
        Paragraph(
            "<b>Generated by StoryCanvas AI</b>",
            SUBTITLE_STYLE
        )
    )

    elements.append(
        Spacer(1, 0.3 * inch)
    )

    elements.append(PageBreak())


def add_story_page(elements, page):

    # -------------------------------------------------
    # Page Heading
    # -------------------------------------------------

    elements.append(
        Paragraph(
            f"Page {page['page']}",
            HEADING_STYLE
        )
    )

    elements.append(
        Spacer(1, 0.1 * inch)
    )

    # -------------------------------------------------
    # Story Illustration
    # -------------------------------------------------

    if os.path.exists(page["image_path"]):

        img = Image(page["image_path"])

        img = resize_image(img)

        elements.append(img)

        elements.append(
            Spacer(1, 0.25 * inch)
        )

    # -------------------------------------------------
    # Story Text
    # -------------------------------------------------

    elements.append(
        Paragraph(
            page["story"],
            BODY_STYLE
        )
    )

    elements.append(
        Spacer(1, 0.25 * inch)
    )

    elements.append(
        Paragraph(
            "────────────────────────────────────────────",
            BODY_STYLE
        )
    )

    elements.append(
        Spacer(1, 0.1 * inch)
    )

    elements.append(
        Paragraph(
            f"StoryCanvas AI &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Page {page['page']}",
            BODY_STYLE
        )
    )

    elements.append(PageBreak())